/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BidResponse } from '../../models/bid-response';

export interface GetAllProducts1$Params {
  Authorization: string;
}

export function getAllProducts1(http: HttpClient, rootUrl: string, params: GetAllProducts1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BidResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllProducts1.PATH, 'get');
  if (params) {
    rb.header('Authorization', params.Authorization, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BidResponse>>;
    })
  );
}

getAllProducts1.PATH = '/api/v1/bids/get-all-bids';
