/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Bid } from '../../models/bid';

export interface GetBidsForProduct$Params {
  Authorization: string;
  productId: number;
}

export function getBidsForProduct(http: HttpClient, rootUrl: string, params: GetBidsForProduct$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Bid>>> {
  const rb = new RequestBuilder(rootUrl, getBidsForProduct.PATH, 'get');
  if (params) {
    rb.header('Authorization', params.Authorization, {});
    rb.query('productId', params.productId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Bid>>;
    })
  );
}

getBidsForProduct.PATH = '/api/v1/bids/get-bids-for-product';
