/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BidRequest } from '../../models/bid-request';
import { BidResponse } from '../../models/bid-response';

export interface SubmitBid$Params {
  Authorization: string;
  'X-Username': string;
      body: BidRequest
}

export function submitBid(http: HttpClient, rootUrl: string, params: SubmitBid$Params, context?: HttpContext): Observable<StrictHttpResponse<BidResponse>> {
  const rb = new RequestBuilder(rootUrl, submitBid.PATH, 'post');
  if (params) {
    rb.header('Authorization', params.Authorization, {});
    rb.header('X-Username', params['X-Username'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BidResponse>;
    })
  );
}

submitBid.PATH = '/api/v1/bids/submit-bid';
