/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvoiceRequest } from '../../models/invoice-request';
import { InvoiceResponse } from '../../models/invoice-response';

export interface CreateInvoice$Params {
  Authorization: string;
      body: InvoiceRequest
}

export function createInvoice(http: HttpClient, rootUrl: string, params: CreateInvoice$Params, context?: HttpContext): Observable<StrictHttpResponse<InvoiceResponse>> {
  const rb = new RequestBuilder(rootUrl, createInvoice.PATH, 'post');
  if (params) {
    rb.header('Authorization', params.Authorization, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvoiceResponse>;
    })
  );
}

createInvoice.PATH = '/api/v1/invoices/create-invoice';
