/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderLineResponse } from '../../models/order-line-response';

export interface FindAllByOrderId$Params {
  Authorization: string;
  'order-id': number;
}

export function findAllByOrderId(http: HttpClient, rootUrl: string, params: FindAllByOrderId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderLineResponse>>> {
  const rb = new RequestBuilder(rootUrl, findAllByOrderId.PATH, 'get');
  if (params) {
    rb.header('Authorization', params.Authorization, {});
    rb.path('order-id', params['order-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OrderLineResponse>>;
    })
  );
}

findAllByOrderId.PATH = '/api/v1/order-lines/order/{order-id}';
