/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductResponse } from '../../models/product-response';

export interface GetProductsForUser$Params {
  Authorization: string;
  'X-Username': string;
}

export function getProductsForUser(http: HttpClient, rootUrl: string, params: GetProductsForUser$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductResponse>>> {
  const rb = new RequestBuilder(rootUrl, getProductsForUser.PATH, 'get');
  if (params) {
    rb.header('Authorization', params.Authorization, {});
    rb.header('X-Username', params['X-Username'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProductResponse>>;
    })
  );
}

getProductsForUser.PATH = '/api/v1/products/get-user-products';
