/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderPaymentRequest } from '../../models/order-payment-request';

export interface CreateOrder$Params {
  Authorization: string;
  'X-Username': string;
  'X-FirstName': string;
  'X-LastName': string;
  'X-Email': string;
      body: OrderPaymentRequest
}

export function createOrder(http: HttpClient, rootUrl: string, params: CreateOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
  const rb = new RequestBuilder(rootUrl, createOrder.PATH, 'post');
  if (params) {
    rb.header('Authorization', params.Authorization, {});
    rb.header('X-Username', params['X-Username'], {});
    rb.header('X-FirstName', params['X-FirstName'], {});
    rb.header('X-LastName', params['X-LastName'], {});
    rb.header('X-Email', params['X-Email'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: parseFloat(String((r as HttpResponse<any>).body)) }) as StrictHttpResponse<number>;
    })
  );
}

createOrder.PATH = '/api/v1/orders/create-order';
