/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartRequest } from '../../models/cart-request';

export interface AddItemToCart$Params {
  Authorization: string;
  'X-Username': string;
      body: CartRequest
}

export function addItemToCart(http: HttpClient, rootUrl: string, params: AddItemToCart$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, addItemToCart.PATH, 'post');
  if (params) {
    rb.header('Authorization', params.Authorization, {});
    rb.header('X-Username', params['X-Username'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

addItemToCart.PATH = '/api/v1/carts/add';
