/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CartItemResponse } from '../models/cart-item-response';
export interface CartResponse {
  cartId?: number;
  items?: Array<CartItemResponse>;
}
