/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CartItemResponse {
  cartItemId?: number;
  description?: string;
  price?: number;
  productId?: number;
  productImageUrl?: string;
  productName?: string;
  quantity?: number;
}
