/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CartItem } from '../models/cart-item';
export interface Cart {
  cartId?: number;
  items?: Array<CartItem>;
  username?: string;
}
