/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Cart } from '../models/cart';
export interface CartItem {
  cart?: Cart;
  cartItemId?: number;
  description?: string;
  price?: number;
  productId?: number;
  productImageUrl?: string;
  productName?: string;
  quantity?: number;
}
