/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsersResponse } from '../../models/users-response';

export interface FindUserByUserId$Params {
  userId: number;
}

export function findUserByUserId(http: HttpClient, rootUrl: string, params: FindUserByUserId$Params, context?: HttpContext): Observable<StrictHttpResponse<UsersResponse>> {
  const rb = new RequestBuilder(rootUrl, findUserByUserId.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsersResponse>;
    })
  );
}

findUserByUserId.PATH = '/api/v1/users/{userId}';
