/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { PaymentResponse } from '../models/payment-response';
import { processPayment } from '../fn/checkout-controller/process-payment';
import { ProcessPayment$Params } from '../fn/checkout-controller/process-payment';

@Injectable({ providedIn: 'root' })
export class CheckoutControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `processPayment()` */
  static readonly ProcessPaymentPath = '/api/v1/checkout/process-payment';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `processPayment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  processPayment$Response(params: ProcessPayment$Params, context?: HttpContext): Observable<StrictHttpResponse<PaymentResponse>> {
    return processPayment(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `processPayment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  processPayment(params: ProcessPayment$Params, context?: HttpContext): Observable<PaymentResponse> {
    return this.processPayment$Response(params, context).pipe(
      map((r: StrictHttpResponse<PaymentResponse>): PaymentResponse => r.body)
    );
  }

}
