/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UsersRequest {
  emailAddress: string;
  firstName: string;
  lastName: string;
  password?: string;
  telephone?: string;
  userId?: number;
  username?: string;
}
