/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UsersResponse {
  emailAddress?: string;
  firstName?: string;
  lastName?: string;
  telephone?: string;
  userId?: number;
  username?: string;
}
