/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Payment } from '../../models/payment';

export interface GetAllPayments$Params {
  Authorization: string;
}

export function getAllPayments(http: HttpClient, rootUrl: string, params: GetAllPayments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Payment>>> {
  const rb = new RequestBuilder(rootUrl, getAllPayments.PATH, 'get');
  if (params) {
    rb.header('Authorization', params.Authorization, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Payment>>;
    })
  );
}

getAllPayments.PATH = '/api/v1/payments/get-all-payments';
