/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvoiceResponse {
  invoiceDate?: string;
  invoiceId?: number;
  invoiceNumber?: string;
  paymentId?: number;
}
