/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PurchaseRequest } from '../models/purchase-request';
export interface OrderRequest {
  buyerUsername?: string;
  orderReference?: string;
  products: Array<PurchaseRequest>;
  totalAmount?: number;
}
