/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Payment {
  amount?: number;
  createdDate?: string;
  lastModifiedDate?: string;
  orderId?: number;
  paymentId?: number;
  paymentMethod?: 'PAYPAL' | 'CREDIT_CARD' | 'DEBIT_CARD' | 'BITCOIN';
  username?: string;
}
