/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface PaymentRequest {
  User?: User;
  amount?: number;
  createdDate?: string;
  isSuccessful?: boolean;
  lastModifiedDate?: string;
  orderId?: number;
  orderReference?: string;
  paymentId?: number;
  paymentMethod?: 'PAYPAL' | 'CREDIT_CARD' | 'DEBIT_CARD' | 'BITCOIN';
}
