/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentRequest {
  amount?: number;
  createdDate?: string;
  isSuccessful?: boolean;
  lastModifiedDate?: string;
  orderId?: number;
  orderReference?: string;
  paymentMethod?: 'PAYPAL' | 'CREDIT_CARD' | 'DEBIT_CARD' | 'BITCOIN';
}
