/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddressRequest {
  city?: string;
  country?: string;
  isBillingAddress?: boolean;
  isShippingAddress?: boolean;
  postalCode?: string;
  state?: string;
  street?: string;
  userId?: number;
}
