/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BidResponse {
  bidAmount?: number;
  bidId?: number;
  bidTime?: string;
  productId?: number;
  username?: string;
}
