/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Category } from '../models/category';
export interface Product {
  availableForBuyNow?: boolean;
  brandName?: string;
  buyNowPrice?: number;
  category?: Category;
  colour?: string;
  description?: string;
  productId?: number;
  productImageUrl?: string;
  productName?: string;
  productSize?: string;
  quantity?: number;
  sold?: boolean;
  startingPrice?: number;
  username?: string;
}
