/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductRequest {
  brandName?: string;
  buyNowPrice?: number;
  categoryId: number;
  colour?: string;
  description: string;
  isAvailableForBuyNow?: boolean;
  isSold?: boolean;
  productImageUrl?: string;
  productName: string;
  productSize?: string;
  quantity?: number;
  startingPrice?: number;
  username?: string;
}
