/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductResponse {
  brandName?: string;
  buyNowPrice?: number;
  categoryId?: number;
  colour?: string;
  description?: string;
  isAvailableForBuyNow?: boolean;
  isSold?: boolean;
  productId?: number;
  productName?: string;
  productSize?: string;
  quantity?: number;
  startingPrice?: number;
  username?: string;
}
