/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductCartResponse {
  description?: string;
  getBuyNowPrice?: number;
  productId?: number;
  productImageUrl?: string;
  productName?: string;
  quantity?: number;
}
