/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderLineResponse {
  brandName?: string;
  buyNowPrice?: number;
  colour?: string;
  description?: string;
  orderLineId?: number;
  productId?: number;
  productImageUrl?: string;
  productName?: string;
  productSize?: string;
  quantity?: number;
  startingPrice?: number;
}
