/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderLineResponse } from '../models/order-line-response';
export interface OrderResponse {
  Buyer?: string;
  createdDate?: string;
  lastModifiedDate?: string;
  orderId?: number;
  orderLineResponse?: Array<OrderLineResponse>;
  reference?: string;
  totalAmount?: number;
}
