/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PurchaseRequest } from '../models/purchase-request';
export interface OrderRequest {
  products: Array<PurchaseRequest>;
  reference?: string;
  totalAmount?: number;
}
