/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderRequest } from '../models/order-request';
import { PaymentRequest } from '../models/payment-request';
export interface OrderPaymentRequest {
  orderRequest?: OrderRequest;
  paymentRequest?: PaymentRequest;
}
