/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PurchaseResponse } from '../models/purchase-response';
export interface OrderResponse {
  Buyer?: string;
  createdDate?: string;
  lastModifiedDate?: string;
  orderId?: number;
  purchasedProducts?: Array<PurchaseResponse>;
  reference?: string;
  totalAmount?: number;
}
