/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PurchaseRequest {
  brandName?: string;
  buyNowPrice?: number;
  colour?: string;
  description?: string;
  productId: number;
  productImageUrl?: string;
  productName?: string;
  productSize?: string;
  quantity?: number;
  startingPrice?: number;
}
