/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PurchaseResponse {
  description?: string;
  price?: number;
  productId?: number;
  productName?: string;
  quantity?: number;
}
