/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import { Injectable } from '@angular/core';
import {catchError, Observable, of, tap} from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createProduct } from '../fn/product-controller/create-product';
import { CreateProduct$Params } from '../fn/product-controller/create-product';
import { getAllProducts } from '../fn/product-controller/get-all-products';
import { GetAllProducts$Params } from '../fn/product-controller/get-all-products';
import { getProduct } from '../fn/product-controller/get-product';
import { GetProduct$Params } from '../fn/product-controller/get-product';
import { ProductResponse } from '../models/product-response';

@Injectable({ providedIn: 'root' })
export class ProductControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createProduct()` */
  static readonly CreateProductPath = '/api/v1/products/create-product';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createProduct()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProduct$Response(params: CreateProduct$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return createProduct(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createProduct$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProduct(params: CreateProduct$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.createProduct$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /** Path part for operation `getProduct()` */
  static readonly GetProductPath = '/api/v1/products';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProduct()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProduct$Response(params?: GetProduct$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return getProduct(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProduct$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProduct(params?: GetProduct$Params, context?: HttpContext): Observable<string> {
    return this.getProduct$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `getAllProducts()` */
  static readonly GetAllProductsPath = '/api/v1/products/get-all-products';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllProducts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllProducts$Response(params?: GetAllProducts$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse[]>> {
    return this.http.get<ProductResponse[]>(this.config.rootUrl + ProductControllerService.GetAllProductsPath, {
      observe: 'response',
      responseType: 'json',
      context: context
    }).pipe(
      map((response: HttpResponse<ProductResponse[]>) => {

        return {
          body: response.body || [],
          headers: response.headers,
          status: response.status,
          statusText: response.statusText,
          url: response.url,
          type: response.type,
          ok: response.ok,
          clone: () => response.clone(),
        } as StrictHttpResponse<ProductResponse[]>;
      })
    );
  }
  /*
  getAllProducts$Response(params?: GetAllProducts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductResponse>>> {
    return getAllProducts(this.http, this.rootUrl, params, context);
  }
*/
  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllProducts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */

  getAllProducts(params?: GetAllProducts$Params, context?: HttpContext): Observable<ProductResponse[]> {
    return this.getAllProducts$Response(params, context).pipe(
      tap((response: StrictHttpResponse<ProductResponse[]>) => {
        console.log('Response:', response);
      }),
      map((response: StrictHttpResponse<ProductResponse[]>) => {
        return response.body; // Return the body directly, which is of type ProductResponse[]
      }),
      catchError((error) => {
        console.error('Error fetching products:', error);
        return of([]); // Return an empty array on error
      })
    );
  }


  /*
  getAllProducts(params?: GetAllProducts$Params, context?: HttpContext): Observable<Array<ProductResponse>> {
    return this.getAllProducts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductResponse>>): Array<ProductResponse> => r.body)
    );
  }
*/
}
